language: ruby
rvm:
 - "2.2.4"
addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - psql -c 'create database github_events_test;' -U viewthespace
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rspec spec
before_install:
  - gem install bundler
