language: ruby
rvm:
 - "2.2.4"
addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - createuser -s viewthespace
  - createdb -O viewthespace -E utf8 github_events_development
  - createdb -O viewthespace -E utf8 github_events_test
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rspec spec
before_install:
  - gem install bundler
